"""empty message

Revision ID: 06a90ba454d6
Revises: dbb0086e5baa
Create Date: 2024-07-20 13:34:29.842945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a90ba454d6'
down_revision = 'dbb0086e5baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('travel')
        batch_op.drop_column('number_user')
        batch_op.drop_column('mood')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('number_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('travel', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('budget', sa.VARCHAR(length=60), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
