"""empty message

Revision ID: 7f6076a233a4
Revises: 2ee21c357e45
Create Date: 2024-08-03 08:28:18.178111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6076a233a4'
down_revision = '2ee21c357e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_dates', sa.ARRAY(sa.Date(), dimensions=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('blog_dates')

    # ### end Alembic commands ###
