"""added new columns

Revision ID: dbb0086e5baa
Revises: cf93fbe6d1e8
Create Date: 2024-07-19 17:27:00.957995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb0086e5baa'
down_revision = 'cf93fbe6d1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('mood', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('travel', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('number_user', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('number_user')
        batch_op.drop_column('travel')
        batch_op.drop_column('mood')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
