"""empty message

Revision ID: 3a888a91bbac
Revises: 7f6076a233a4
Create Date: 2024-08-03 11:49:58.444204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a888a91bbac'
down_revision = '7f6076a233a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('blog_dates',
               existing_type=postgresql.ARRAY(sa.DATE()),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('blog_dates',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.DATE()),
               existing_nullable=True)

    # ### end Alembic commands ###
