"""Dropped some blog columns

Revision ID: cf93fbe6d1e8
Revises: ae435af86d6a
Create Date: 2024-07-17 12:23:21.649978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf93fbe6d1e8'
down_revision = 'ae435af86d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
